# Generated by Django 4.1.5 on 2023-02-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_link',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
