# Generated by Django 4.1.5 on 2023-02-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certify',
            name='certify_all',
            field=models.FileField(blank=True, null=True, upload_to='certificates_all'),
        ),
    ]
