# Generated by Django 4.1.5 on 2023-02-18 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_certify_certify_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='certify',
            name='author',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certify',
            name='certify',
            field=models.FileField(blank=True, upload_to='certificates'),
        ),
    ]
