# Generated by Django 4.1.5 on 2023-02-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_postreport_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
