# Generated by Django 4.1.5 on 2023-02-26 03:59

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_do_exercise_listen_music_listen_musictranslation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listen_musictranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='listen_musictranslation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='listen_musictranslation',
            name='master',
        ),
        migrations.AddField(
            model_name='do_exercisetranslation',
            name='youtube_exercise',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AddField(
            model_name='storytranslation',
            name='youtube_story',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.DeleteModel(
            name='Listen_Music',
        ),
        migrations.DeleteModel(
            name='Listen_MusicTranslation',
        ),
    ]
