# Generated by Django 4.1.5 on 2023-02-26 04:01

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_listen_musictranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tutorial_video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=''),
        ),
    ]
