# Generated by Django 4.1.5 on 2023-02-26 04:03

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_tutorial_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tutorial_video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
