# Generated by Django 4.1.5 on 2023-02-26 04:04

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_tutorial_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storytranslation',
            name='youtube_story',
            field=embed_video.fields.EmbedVideoField(default=''),
        ),
    ]
