# Generated by Django 4.1.5 on 2023-02-26 04:10

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_storytranslation_youtube_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storytranslation',
            name='youtube_story',
        ),
        migrations.AddField(
            model_name='story',
            name='youtube_story',
            field=embed_video.fields.EmbedVideoField(default=''),
        ),
    ]
