# Generated by Django 4.1.5 on 2023-02-26 04:12

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_storytranslation_youtube_story_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tutorial_video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
