# Generated by Django 4.1.5 on 2023-02-26 04:18

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_story_youtube_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tutorial_video',
        ),
        migrations.RemoveField(
            model_name='story',
            name='youtube_story',
        ),
        migrations.AddField(
            model_name='storytranslation',
            name='youtube_story',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
